name: CI

on: [pull_request]

permissions:
  contents: read

env:
  NODE_VERSION: 18.x

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
      - name: Build
        uses: borales/actions-yarn@v4
        env:
          CI: true
        with:
          cmd: build
